// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6NomriUWrP83tvCGoeHcXyTDhH1I_bj0',
    appId: '1:879929224342:web:1c3ed6dab25e5aa656a6b7',
    messagingSenderId: '879929224342',
    projectId: 'kesehatanku-project',
    authDomain: 'kesehatanku-project.firebaseapp.com',
    storageBucket: 'kesehatanku-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Tl5kb1BkKUtYIvFYyNRZh_Qd7wDSZi8',
    appId: '1:879929224342:android:5511d8725af1c69f56a6b7',
    messagingSenderId: '879929224342',
    projectId: 'kesehatanku-project',
    storageBucket: 'kesehatanku-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbhVtn_n_ZkFSHjoGy3QSCwm5BJBl2X_4',
    appId: '1:879929224342:ios:54731ae8f223e6e156a6b7',
    messagingSenderId: '879929224342',
    projectId: 'kesehatanku-project',
    storageBucket: 'kesehatanku-project.firebasestorage.app',
    iosBundleId: 'com.example.kesehatanKu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbhVtn_n_ZkFSHjoGy3QSCwm5BJBl2X_4',
    appId: '1:879929224342:ios:54731ae8f223e6e156a6b7',
    messagingSenderId: '879929224342',
    projectId: 'kesehatanku-project',
    storageBucket: 'kesehatanku-project.firebasestorage.app',
    iosBundleId: 'com.example.kesehatanKu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6NomriUWrP83tvCGoeHcXyTDhH1I_bj0',
    appId: '1:879929224342:web:50b6b5f66743200756a6b7',
    messagingSenderId: '879929224342',
    projectId: 'kesehatanku-project',
    authDomain: 'kesehatanku-project.firebaseapp.com',
    storageBucket: 'kesehatanku-project.firebasestorage.app',
  );
}
